### ISSUE TITLE
Green slime balls vs. mesecons glue green balls

### ISSUE THREAD

**Issue by bell07** [blert2112/mobs_more_monsters#4]
Unsure if accepted, but the slime balls and mesecons_materials:glue seems identically (same graphic), maybe it is beter to set an alias if mesecons found. I set it by me locally by:
```
diff --git a/mobs_slimes/greenslimes.lua b/mobs_slimes/greenslimes.lua
index 5cebc82..e78c46c 100644
--- a/mobs_slimes/greenslimes.lua
+++ b/mobs_slimes/greenslimes.lua
@@ -135,7 +135,11 @@ mobs:register_egg("mobs_slimes:green_medium", "Medium Green Slime", "green_slime
 mobs:register_egg("mobs_slimes:green_big", "Big Green Slime", "green_slime_front.png", 0)
 
 -- crafts
-minetest.register_craftitem("mobs_slimes:green_slimeball", {
-       image = "jeija_glue.png",
-       description="Green Slime Ball",
-})
+if minetest.get_modpath("mesecons_materials") then
+       minetest.register_alias("mobs_slimes:green_slimeball", "mesecons_materials:glue")
+else
+       minetest.register_craftitem("mobs_slimes:green_slimeball", {
+               image = "jeija_glue.png",
+               description="Green Slime Ball",
+       })
+end
```

**Comment by taikedz** [comment]
"slime balls" and "mesecons glue" do indeed use the same graphic...

A slime ball, however, **is not** a mesecons glue.

Just because two things use the same texture does not mean they are intended to be the same material.

Of course, it is confusing to use the same graphic unaltered for a different material, so I would suggest using a `^[colorize` statement on the slime ball instead to differentiate...

Maybe `^[colorize:yellow:100` ...?

**Comment by bell07** [comment]
> A slime ball, however, is not a mesecons glue.

That is pity, I had the asumption it is like in MC, the Slime drops slimeballs that are important ingredient in technic (for Sticky Piston)
Ok. What I can do in MT with dropped slime balls?

**Comment by taikedz** [comment]
Can't do anything with slime balls directly. It just makes sense for slimes to drop slime balls.

I run a server where I've added some recipes involving the slime balls.
